// Shared types for the postal-monitor example.
//
// Keep this module free of any Node.js or postal runtime imports so it can
// be safely imported by both the monitor process and reporter clients
// without triggering side effects.
//
// The ChannelRegistry augmentation tells postal what payload types flow on
// each topic of the "monitor" channel — compile-time only, zero runtime cost.

/** Payload published when a task begins executing. */
export type TaskStartedPayload = {
    /** Unique identifier for this task run. Generated by the reporter. */
    taskId: string;
    /** npm package name being operated on (e.g. "postal"). */
    package: string;
    /** The pnpm script/command being run (e.g. "test", "lint", "build"). */
    command: string;
    /** OS process ID of the spawned child process. */
    pid: number;
};

/** Payload published when a task finishes (success or failure). */
export type TaskFinishedPayload = {
    /** Unique identifier matching the corresponding task.started event. */
    taskId: string;
    /** npm package name being operated on. */
    package: string;
    /** The pnpm script/command that was run. */
    command: string;
    /** OS process ID of the spawned child process. */
    pid: number;
    /** True if the process exited with code 0. */
    success: boolean;
    /** Wall-clock duration in milliseconds from start to finish. */
    duration: number;
    /** Error message if the process failed, undefined on success. */
    error?: string;
};

// --- Channel registry augmentation ---
//
// Topics used in this example:
//   monitor: task.started  — emitted by each reporter when a task begins
//   monitor: task.finished — emitted by each reporter when a task ends

declare module "postal" {
    interface ChannelRegistry {
        monitor: {
            "task.started": TaskStartedPayload;
            "task.finished": TaskFinishedPayload;
        };
    }
}
